# -*- coding: utf-8 -*-
"""README.md

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gOng0Kb_6SJtg6M-tQ2wwsSb5aQuYnIZ
"""



"""## **IRIS FLOWER CLASSIFICATION:**

Iris flower has three species; setosa, versicolor, and virginica, which differs according to their measurements. Now assume that you have the measurements of the iris flowers according to their species, and here your task is to train a machine learning model that can learn from the measurements of the iris species and classify them.


### **Dataset Used :** "Iris.csv"


### **Python libraries used :**
*   NUMPY
*   PANDAS
*   SKLEARN
*   MATPLOTLIB
*   SEABORN



## **Applied :**
DATA PROCESSING

DATA CLEANING

DATA VISUALIZATION

MODEL BUILDING

APPROACHES OF DIFFERENT MODELS

# **Solved with :**
Logistic Regression (LR)

Linear Discriminant Analysis (LDA)

Classification and Regression Trees (CART)

Gaussian Naive Bayes (NB)

Support Vector Machines (SVM)

## **Technologies Used** : 
Python, Machine Learning

## **IDE** - Google Colab

"""